### ISSUE TITLE
Generate "Plural Forms" header automatically

### ISSUE THREAD

**Issue by leeper** [RL10N/msgtools#13]
Based on language, it should be possible to automatically populate the Plural Forms header value when using `make_translation` based on the rules described here: http://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/Plural-forms.html

**Comment by richierocks** [comment]
There's a great lookup with all the plural form strings here:

https://localization-guide.readthedocs.org/en/latest/l10n/pluralforms.html

**Comment by leeper** [comment]
@richierocks  :+1: Just added this as a CSV: https://github.com/leeper/msgtools/blob/master/data/PluralFormHeaders.csv
