### ISSUE TITLE
Object "res" does not exist at line 30 in install_translations.R

### ISSUE THREAD

**Issue by ofurkusi** [RL10N/msgtools#15]
Using the current master branch, `install_translations()` throws an error 

```
Error in nrow(res) : object 'res' not found
```

looks like some curly braces are missing

**Comment by leeper** [comment]
Thanks. Let me investigate. That code is adapted from another place, so I'll need to retrace why it's written the way it is.

**Comment by leeper** [comment]
This should be fixed as of https://github.com/RL10N/msgtools/commit/b7aac40f252504cfc5d1e852c2b8c734cb004078
